name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Node
      run: sudo apt-get install nodejs
    
    - name: Install NPM
      run: sudo apt install npm
    
    - name: Install dependencies
      run: npm install express

    - name: Run tests
      run: node server.js
